
############################################################
#
# Server 服务端相关配置
#
############################################################
# 配置API的端口号
server:
  port: 8090
  tomcat:
    acceptCount: 1
    max-connections: 1
    max-threads: 1
#关闭安全限制


